### ISSUE TITLE
Record.get does not allow for integer "paths"

### ISSUE THREAD

**Issue by adamgoose** [hoxton-one/deepstream.io-client-js#9]
I'm attempting to use a record for an "unread count" tracker in my new chat app. The desired format is something like this:

```js
var myId = 1; // for example
var OtherUserId = 2; // for example
var conversationId = '1&2'; // for example
var counts = ds.record.getRecord('unread_counts.' + conversationId);

// "whenReady" is respected in the following examples

function incrementForOtherUser() {
  var newCount = counts.get(otherUserId) + 1;
  counts.set(otherUserId, newCount);
}
```

Essentially, the record is a `key: value` array with two keys. Both the keys and the values are integers.

When I try to do this, I get an exception `this._path.split` is not a function. Trace below (forgive the Angular bits).

```
TypeError: this._path.split is not a function
    at 49.JsonPath._tokenize (http://bridgeconx.app/build/js/core-bd895c80.js:36701:25)
    at new 49.JsonPath (http://bridgeconx.app/build/js/core-bd895c80.js:36640:7)
    at 53.Record._getPath (http://bridgeconx.app/build/js/core-bd895c80.js:37585:25)
    at 53.Record.get (http://bridgeconx.app/build/js/core-bd895c80.js:37248:16)
    at http://bridgeconx.app/build/js/core-bd895c80.js:38907:58
    at 53.Record.whenReady (http://bridgeconx.app/build/js/core-bd895c80.js:37417:3)
    at incrementUnreadCountForOtherUser (http://bridgeconx.app/build/js/core-bd895c80.js:38906:25)
    at Scope.link.scope.sendMessage (http://bridgeconx.app/build/js/core-bd895c80.js:38832:15)
    at $parseFunctionCall (http://bridgeconx.app/build/js/core-bd895c80.js:12415:18)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (http://bridgeconx.app/build/js/core-bd895c80.js:21577:17)
```

It seems as though `JsonPath._tokenize` doesn't respect integer "keys". This could possibly be fixed by casting the provided path to a string before passing it to the `_tokenize` method.

**Comment by adamgoose** [comment]
Indeed, casting the path to a string before passing it to `Record.get` solves it. I imagine you can come up with a more graceful way to handle it.

**Comment by yasserf** [comment]
Agreed, implicit string casting will solve this gracefully. We'll add it to the next release.
